### ISSUE TITLE
Cycle through thumbnail sizes on the fly

### ISSUE THREAD

**Issue by noctuid** [occivink/mpv-gallery-view#17]
It would be nice to dynamically increase/decrease the size of thumbnails with a keybinding.

**Comment by occivink** [comment]
since that would be relatively difficult to expose as configuration, my preferred solution would be to expose a `script_message` that allows reconfiguring the geometry, such that this could be implemented by a separate script

**Comment by Waiifu** [comment]
Hey, I just made a pull request a couple hours ago and noticed this issue was open. What you're asking for is solved for in it, at least for playlist-view for now (as I did not bother with contact sheet yet since I don't personally use it). https://github.com/occivink/mpv-gallery-view/pull/24

**Comment by occivink** [comment]
This is now possible, see #24

**Comment by occivink** [comment]
My guess is that you forgot to copy `gallery.lua`. In mpv/scripts you need a folder named `lib.disable` which contains the `gallery.lua` file from this repo. 
To help troubleshoot this, launch mpv from the commandline and report any error that occur. Or start mpv with the option '--log-file=log' and upload the log file.

Also nice file manager, what is it?

**Comment by RafeeDaBoy** [comment]
Thanks a lot. I forgot the `lib.disable` folder. It works now. 

Btw, how do I exactly run [this](https://github.com/occivink/mpv-gallery-view#limitations)?

The file manager is One Commander 

![image](https://user-images.githubusercontent.com/69535896/151666427-9f1a6f1f-6167-4073-a82e-9377db3c2e65.png)

**Comment by occivink** [comment]
You mean the snippet for deleting thumbnails? This is a shell script, I do not have an equivalent solution for windows, you'll have to find one yourself.

**Comment by RafeeDaBoy** [comment]
Alright, thanks a lot for your help!

**Comment by RafeeDaBoy** [comment]
Also, when creating copies copies of `gallery-thumbgen.lua`, does the naming need to be specific or just `gallery-thumbgen.lua1`?

**Comment by occivink** [comment]
the naming should not matter, although you probably should keep the .lua extension. So `gallery-thumbgen-1.lua` for example.

**Comment by RafeeDaBoy** [comment]
Yes, that's what I meant. Thanks
